/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

interface nsICacheEntry;
interface nsIApplicationCache;

[scriptable, uuid(83f2170b-895c-44f1-96c8-5b86e120dead)]
interface nsICacheEntryOpenCallback : nsISupports
{
  /**
   * Callback to perform any validity checks before the entry should be used.
   * Called before onCacheEntryAvailable callback.
   *
   * @param aEntry
   *    An entry to examine.  Consumer has to decide whether the entry is
   *    valid or not.
   * @param aApplicationCache
   *    Optional, application the entry has been found at, if any.
   * @return
   *    True when the entry is found valid.  onCacheEntryAvailable will then
   *    be called with the given entry.
   *    False when the entry is found invalid.  onCacheEntryAvailable will then
   *    be called witha a newly created entry.
   *
   * NOTE: This callback is invoked on the cache background thread.
   */
  boolean onCacheEntryCheck(in nsICacheEntry aEntry,
                            in nsIApplicationCache aApplicationCache);

  /**
   * Callback implemented by consumers of nsICacheStorage fetching
   * result of the cache async open request.
   *
   * @param aEntry
   *    The entry bound to the originally requested URI.  May be null when
   *    loading from a particular application cache and the URI has not
   *    been found in that application cache.
   * @param aNew
   *    Whether no data so far has been stored for this entry, i.e. reading
   *    it will just fail.  When aNew is true, a server request should be
   *    made and data stored to this new entry.
   * @param aApplicationCache
   *    When an entry had been found in an application cache, this is the
   *    given application cache.  It should be associated with the loading
   *    channel.
   * @param aResult
   *    Result of request.  This may be a failure only when one of these
   *    issues occur:
   *    - the cache storage service could not be started due to some unexpected
   *      faulure
   *    - there is not enough disk space to create new entries
   *    - cache entry was not found in a given application cache
   *
   * NOTE: In the current implementation this callback is invoked on the main thread
   *       however, we would like to call this on a different thread in the future.
   */
  void onCacheEntryAvailable(in nsICacheEntry aEntry,
                             in boolean aNew,
                             in nsIApplicationCache aApplicationCache,
                             in nsresult aResult);
};
